### ISSUE TITLE
Error When Generating Shared Access URL

### ISSUE THREAD

**Issue by olifolkerd** [beberlei/azure-blob-storage#7]
When attempting to call the generateSharedAccessUrl method on the BlobClient i get an "Undefined property" error returned for sharedAccessSignatureCredentials within the function

**Comment by olifolkerd** [comment]
on further investigation the following line needs to be added to the constructor for Blob Client:

$this->sharedAccessSignatureCredentials = new SharedAccessSignature($accountName, $accountKey, false);

**Comment by georgezams** [comment]
Hi, any help would be appreciated, i am trying to set the header for caching on putBlobData like so 
$metadata= array('x-ms-blob-cache-control' => 'public, max-age=31556926');
BlobStorage::putBlobData($container, $filename, File::get($blobFileName), $metadata);

Getting an error 
Metadata name does not adhere to metadata naming conventions

Any suggestions?
